name: CI/CD Pipeline for SQL-ANALYZER on CatDev

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_CATDEV }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no -p 2324 ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST_CATDEV }} '
        cd pincode.vtb-hack &&
        eval $(ssh-agent -s) &&
        echo "${{ secrets.SSH_PASSPHRASE }}" | SSH_ASKPASS=/bin/cat ssh-add ~/.ssh/id_rsa_github &&
        git pull &&
        sudo docker compose up -d --build &&
        sudo docker system prune -af
        '
